// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllContexts():Promise<Array<string>>;

export function GetCurrentContext():Promise<string>;

export function MergeIntoDefault(arg1:string):Promise<main.MergeResult>;

export function SelectKubeconfig():Promise<string>;

export function SwitchContext(arg1:string):Promise<void>;
