// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllContexts() {
  return window['go']['main']['App']['GetAllContexts']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function MergeIntoDefault(arg1) {
  return window['go']['main']['App']['MergeIntoDefault'](arg1);
}

export function SelectKubeconfig() {
  return window['go']['main']['App']['SelectKubeconfig']();
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}
