// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function DeleteContextForPath(arg1, arg2) {
  return window['go']['main']['App']['DeleteContextForPath'](arg1, arg2);
}

export function GetAllContexts() {
  return window['go']['main']['App']['GetAllContexts']();
}

export function GetAllContextsForPath(arg1) {
  return window['go']['main']['App']['GetAllContextsForPath'](arg1);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetCurrentContextForPath(arg1) {
  return window['go']['main']['App']['GetCurrentContextForPath'](arg1);
}

export function GetDefaultWSLUser(arg1) {
  return window['go']['main']['App']['GetDefaultWSLUser'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function ListWSLDistros() {
  return window['go']['main']['App']['ListWSLDistros']();
}

export function MergeIntoDefault(arg1) {
  return window['go']['main']['App']['MergeIntoDefault'](arg1);
}

export function MergeIntoTarget(arg1, arg2) {
  return window['go']['main']['App']['MergeIntoTarget'](arg1, arg2);
}

export function ResolveTargetKubeconfig(arg1) {
  return window['go']['main']['App']['ResolveTargetKubeconfig'](arg1);
}

export function SelectKubeconfig() {
  return window['go']['main']['App']['SelectKubeconfig']();
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}

export function SwitchContextForPath(arg1, arg2) {
  return window['go']['main']['App']['SwitchContextForPath'](arg1, arg2);
}

export function TestFileExists(arg1) {
  return window['go']['main']['App']['TestFileExists'](arg1);
}
