// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteContext(arg1:string):Promise<void>;

export function DeleteContextForPath(arg1:string,arg2:string):Promise<void>;

export function GetAllContexts():Promise<Array<string>>;

export function GetAllContextsForPath(arg1:string):Promise<Array<string>>;

export function GetClusterInfoForCurrentContext(arg1:string):Promise<main.ClusterInfo>;

export function GetContextDetails(arg1:string,arg2:string):Promise<main.ContextDetails>;

export function GetContextsWithCurrent():Promise<Array<main.ContextInfo>>;

export function GetCurrentContext():Promise<string>;

export function GetCurrentContextForPath(arg1:string):Promise<string>;

export function GetCurrentNamespace(arg1:string,arg2:string):Promise<string>;

export function GetCurrentNamespaceForPath(arg1:string,arg2:string):Promise<string>;

export function GetDefaultWSLUser(arg1:string):Promise<string>;

export function GetOS():Promise<string>;

export function ListNamespaces(arg1:string,arg2:string):Promise<Array<string>>;

export function ListNamespacesForPath(arg1:string,arg2:string):Promise<Array<string>>;

export function ListWSLDistros():Promise<Array<string>>;

export function MergeIntoDefault(arg1:string):Promise<main.MergeResult>;

export function MergeIntoTarget(arg1:string,arg2:string):Promise<main.MergeResult>;

export function QuickSwitchContext(arg1:string):Promise<void>;

export function ResolveTargetKubeconfig(arg1:main.TargetSelection):Promise<string>;

export function SearchContexts(arg1:string):Promise<Array<main.ContextInfo>>;

export function SelectKubeconfig():Promise<string>;

export function SetNamespaceForPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowContextSearchDialog():Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function SwitchContextForPath(arg1:string,arg2:string):Promise<void>;

export function SwitchNamespace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestClusterConnectivity(arg1:string,arg2:string):Promise<main.ClusterInfo>;

export function TestFileExists(arg1:string):Promise<boolean>;
