// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function DeleteContextForPath(arg1, arg2) {
  return window['go']['main']['App']['DeleteContextForPath'](arg1, arg2);
}

export function GetAllContexts() {
  return window['go']['main']['App']['GetAllContexts']();
}

export function GetAllContextsForPath(arg1) {
  return window['go']['main']['App']['GetAllContextsForPath'](arg1);
}

export function GetAllContextsForTray() {
  return window['go']['main']['App']['GetAllContextsForTray']();
}

export function GetClusterInfoForCurrentContext(arg1) {
  return window['go']['main']['App']['GetClusterInfoForCurrentContext'](arg1);
}

export function GetContextDetails(arg1, arg2) {
  return window['go']['main']['App']['GetContextDetails'](arg1, arg2);
}

export function GetContextsWithCurrent() {
  return window['go']['main']['App']['GetContextsWithCurrent']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetCurrentContextForPath(arg1) {
  return window['go']['main']['App']['GetCurrentContextForPath'](arg1);
}

export function GetCurrentContextForTray() {
  return window['go']['main']['App']['GetCurrentContextForTray']();
}

export function GetCurrentNamespace(arg1, arg2) {
  return window['go']['main']['App']['GetCurrentNamespace'](arg1, arg2);
}

export function GetCurrentNamespaceForPath(arg1, arg2) {
  return window['go']['main']['App']['GetCurrentNamespaceForPath'](arg1, arg2);
}

export function GetDefaultWSLUser(arg1) {
  return window['go']['main']['App']['GetDefaultWSLUser'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetTargetKubeconfig() {
  return window['go']['main']['App']['GetTargetKubeconfig']();
}

export function ListNamespaces(arg1, arg2) {
  return window['go']['main']['App']['ListNamespaces'](arg1, arg2);
}

export function ListNamespacesForPath(arg1, arg2) {
  return window['go']['main']['App']['ListNamespacesForPath'](arg1, arg2);
}

export function ListWSLDistros() {
  return window['go']['main']['App']['ListWSLDistros']();
}

export function MergeIntoDefault(arg1) {
  return window['go']['main']['App']['MergeIntoDefault'](arg1);
}

export function MergeIntoTarget(arg1, arg2) {
  return window['go']['main']['App']['MergeIntoTarget'](arg1, arg2);
}

export function QuickSwitchContext(arg1) {
  return window['go']['main']['App']['QuickSwitchContext'](arg1);
}

export function ResolveTargetKubeconfig(arg1) {
  return window['go']['main']['App']['ResolveTargetKubeconfig'](arg1);
}

export function SearchContexts(arg1) {
  return window['go']['main']['App']['SearchContexts'](arg1);
}

export function SelectKubeconfig() {
  return window['go']['main']['App']['SelectKubeconfig']();
}

export function SetFloatingMode(arg1) {
  return window['go']['main']['App']['SetFloatingMode'](arg1);
}

export function SetNamespaceForPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNamespaceForPath'](arg1, arg2, arg3);
}

export function SetTargetKubeconfig(arg1) {
  return window['go']['main']['App']['SetTargetKubeconfig'](arg1);
}

export function ShowContextSearchDialog() {
  return window['go']['main']['App']['ShowContextSearchDialog']();
}

export function ShowWindowFromTray() {
  return window['go']['main']['App']['ShowWindowFromTray']();
}

export function StartInFloatingMode() {
  return window['go']['main']['App']['StartInFloatingMode']();
}

export function SwitchContext(arg1) {
  return window['go']['main']['App']['SwitchContext'](arg1);
}

export function SwitchContextForPath(arg1, arg2) {
  return window['go']['main']['App']['SwitchContextForPath'](arg1, arg2);
}

export function SwitchContextForTray(arg1) {
  return window['go']['main']['App']['SwitchContextForTray'](arg1);
}

export function SwitchNamespace(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchNamespace'](arg1, arg2, arg3);
}

export function TestClusterConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestClusterConnectivity'](arg1, arg2);
}

export function TestFileExists(arg1) {
  return window['go']['main']['App']['TestFileExists'](arg1);
}

export function ToggleFloatingMode() {
  return window['go']['main']['App']['ToggleFloatingMode']();
}

export function ToggleFloatingWidget() {
  return window['go']['main']['App']['ToggleFloatingWidget']();
}

export function WidgetCollapse() {
  return window['go']['main']['App']['WidgetCollapse']();
}

export function WidgetExpand() {
  return window['go']['main']['App']['WidgetExpand']();
}

export function WidgetFullGUI() {
  return window['go']['main']['App']['WidgetFullGUI']();
}
